export { default as GetPrice } from "./get-price"
export { default as Products } from "./products"
export { default as Product } from "./product"
export { default as Gallery } from "./gallery"
export { default as ProductSpecifications } from "./specifications"
